# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Sahiru/Lab9/NanoProcessor/NanoProcessor/NanoProcessor.cache/wt [current_project]
set_property parent.project_path D:/Sahiru/Lab9/NanoProcessor/NanoProcessor/NanoProcessor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo d:/Sahiru/Lab9/NanoProcessor/NanoProcessor/NanoProcessor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/Sahiru/Lab9/Pamudu/3-bit adder/3-bit adder.srcs/sources_1/new/Adder_3_bit.vhd}
  {D:/Sahiru/Lab9/Pamudu/Program Counter/programcounter.srcs/sources_1/new/D_FF.vhd}
  {D:/Sahiru/LabFiles/New folder/Lab4/Lab4.srcs/sources_1/new/Decode_3_to_8.vhd}
  {D:/Sahiru/LabFiles/New folder/Lab4/Lab4.srcs/sources_1/new/Decoder_2_to_4.vhd}
  {D:/Sahiru/LabFiles/New folder/Lab3/Lab3.srcs/sources_1/new/FA.vhd}
  {D:/Sahiru/Lab9/Pamudu/3-bit adder/3-bit adder.srcs/sources_1/new/HA.vhd}
  {D:/Sahiru/LabFiles/New folder/L7/L7.srcs/sources_1/new/LUT_16_7.vhd}
  D:/Sahiru/Lab9/NanoProcessor/ProgramRom/ProgramRom.srcs/sources_1/new/LUT_8_12.vhd
  D:/Sahiru/Lab9/NanoProcessor/Lab9_10/Lab9_10.srcs/sources_1/new/Mux_2_to_1.vhd
  D:/Sahiru/Lab9/NanoProcessor/Lab9_10/Lab9_10.srcs/sources_1/new/Mux_2way_3bit.vhd
  D:/Sahiru/Lab9/NanoProcessor/Mux2way4bit/Mux2way4bit.srcs/sources_1/new/Mux_2way_4bit.vhd
  D:/Sahiru/Lab9/NanoProcessor/Mux_8way_4bit/Mux_8way_4bit.srcs/sources_1/imports/new/Mux_8_to_1.vhd
  D:/Sahiru/Lab9/NanoProcessor/Mux_8way_4bit/Mux_8way_4bit.srcs/sources_1/new/Mux_8way_4bit.vhd
  {D:/Sahiru/Lab9/Pamudu/Program Counter/programcounter.srcs/sources_1/new/PC.vhd}
  {D:/Sahiru/LabFiles/New folder/Lab3/Lab3.srcs/sources_1/new/RCA_4.vhd}
  {D:/Sahiru/LabFiles/New folder/L7/L7.srcs/sources_1/imports/sources_1/imports/new/Slow_Clk.vhd}
  D:/Sahiru/Lab9/Add_sub_4bit/add_sub_4bit/add_sub_4bit.srcs/sources_1/new/add_sub_4bit.vhd
  D:/Sahiru/Lab9/bit4reg/bit4reg/bit4reg.srcs/sources_1/new/bit4reg.vhd
  D:/Sahiru/Lab9/In_decoder/In_decoder/In_decoder.srcs/sources_1/new/instrctuion_decoder.vhd
  D:/Sahiru/Lab9/bit4reg/bit4reg/bit4reg.srcs/sources_1/new/register_bank.vhd
  D:/Sahiru/Lab9/NanoProcessor/NanoProcessor/NanoProcessor.srcs/sources_1/new/NanoProcessor.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Sahiru/LabFiles/New folder/Basys3Labs.xdc}}
set_property used_in_implementation false [get_files {{D:/Sahiru/LabFiles/New folder/Basys3Labs.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top NanoProcessor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef NanoProcessor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file NanoProcessor_utilization_synth.rpt -pb NanoProcessor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
